### PR TITLE
ppx: qualify usages of stdlib infix operators

### PR DESCRIPTION
**Pull request by jchavarri**

### CODE REVIEW

**Review by davesnx — APPROVED** [review]
Much needed PR

**Review by andreypopp — COMMENTED** [review]
for the cases where type is already known — I'd use type specific equality operator — e.g. `Stdlib.Int.equal` for `int` and so on

By the way `not` should also be qualified.

**Comment by jchavarri** [comment]
> for the cases where type is already known — I'd use type specific equality operator — e.g. `Stdlib.Int.equal` for `int` and so on

I'm not sure, this will be adding more runtime without a lot of benefits, see example [in playground](https://melange.re/v4.0.0/playground/?language=OCaml&code=bGV0IGZvbyAoYTogc3RyaW5nKSAoYjogc3RyaW5nKSA9IEpzLmxvZyAoYSA9IGIpCmxldCBmb28yIChhOiBzdHJpbmcpIChiOiBzdHJpbmcpID0gSnMubG9nIChTdHJpbmcuZXF1YWwgYSBiKQ%3D%3D&live=off).

**Comment by andreypopp** [comment]
> I'm not sure, this will be adding more runtime without a lot of benefits, see example [in playground](https://melange.re/v4.0.0/playground/?language=OCaml&code=bGV0IGZvbyAoYTogc3RyaW5nKSAoYjogc3RyaW5nKSA9IEpzLmxvZyAoYSA9IGIpCmxldCBmb28yIChhOiBzdHJpbmcpIChiOiBzdHJpbmcpID0gSnMubG9nIChTdHJpbmcuZXF1YWwgYSBiKQ%3D%3D&live=off)

wow, didn't know that, then it's good as it is, thank you!

**Comment by jchavarri** [comment]
> By the way `not` should also be qualified.

Done in https://github.com/melange-community/melange-json/pull/11/commits/d2f84975903d1395bd2092889edbf6287370b16e.

**Review by andreypopp — APPROVED** [review]

**Comment by anmonteiro** [comment]
> > for the cases where type is already known — I'd use type specific equality operator — e.g. `Stdlib.Int.equal` for `int` and so on
> 
> I'm not sure, this will be adding more runtime without a lot of benefits, see example [in playground](https://melange.re/v4.0.0/playground/?language=OCaml&code=bGV0IGZvbyAoYTogc3RyaW5nKSAoYjogc3RyaW5nKSA9IEpzLmxvZyAoYSA9IGIpCmxldCBmb28yIChhOiBzdHJpbmcpIChiOiBzdHJpbmcpID0gSnMubG9nIChTdHJpbmcuZXF1YWwgYSBiKQ%3D%3D&live=off):
> 
> ```ocaml
> let foo (a: string) (b: string) = Js.log (a = b)
> let foo2 (a: string) (b: string) = Js.log (String.equal a b)
> ```
> 
> produces:
> 
> ```js
> function foo(a, b) {
>   console.log(a === b);
> }
> 
> function foo2(a, b) {
>   console.log(Stdlib__String.equal(a, b));
> }
> ```

oh interesting. I think this is because `String.equal` is a `external ..` in the `.ml` but a `val` in the `.mli`.

**Comment by andreypopp** [comment]
> oh interesting. I think this is because String.equal is an external .. in the .ml but a val in the .mli.

@anmonteiro should we fix this?

**Comment by anmonteiro** [comment]
> > oh interesting. I think this is because String.equal is an external .. in the .ml but a val in the .mli.
> 
> @anmonteiro should we fix this?

I think it's a good idea -- I'll play with it

**Pull request merged**
